name: hello-world
  on: push
  jobs: 
    test: 
      runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v4
            name: test-huyni
            run: make say-hello